#!/usr/bin/env bash
set -euo pipefail

APP_DIR="$HOME/.termux-avid-kiya"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAUNCHER_SRC="$PROJECT_DIR/scripts/launcher.sh"
AVID_SRC="$PROJECT_DIR/scripts/avid.sh"
WEB_SRC="$PROJECT_DIR/web"
AGENT_SRC="$PROJECT_DIR/agent"
CONFIG_SRC="$PROJECT_DIR/config.example"
LAUNCHER_DST="$APP_DIR/launcher.sh"
AVID_DST="$APP_DIR/bin/avid"
WEB_DST="$APP_DIR/web"
AGENT_DST="$APP_DIR/agent"
CONFIG_DST="$APP_DIR/config"
BASHRC="$HOME/.bashrc"
FISH_CONF_DIR="$HOME/.config/fish/conf.d"
FISH_CONF="$FISH_CONF_DIR/avid-kiya-launcher.fish"
MARK_BEGIN="# >>> AVID_KIYA_TERMUX_UBUNTU_LAUNCHER >>>"
MARK_END="# <<< AVID_KIYA_TERMUX_UBUNTU_LAUNCHER <<<"

msg() { printf '%s\n' "$*"; }
has() { command -v "$1" >/dev/null 2>&1; }

pkg_missing() {
  missing=""
  for p in "$@"; do
    if ! dpkg -s "$p" >/dev/null 2>&1; then
      missing="$missing $p"
    fi
  done
  printf '%s\n' "$missing"
}

pkg_install_missing() {
  missing="$(pkg_missing "$@")"
  if [ -n "$(printf '%s' "$missing" | tr -d ' ')" ]; then
    msg "[+] Installing missing Termux packages:$missing"
    pkg install -y $missing || true
  else
    msg "[✓] Termux packages already installed. Skipping download."
  fi
}

ask_update() {
  msg "[?] Check repositories for updates? This uses a little internet. [y/N]"
  read -r ans
  case "$ans" in y|Y|yes|YES) pkg update -y || true ;; *) msg "[i] Skipping pkg update." ;; esac
}

if ! has pkg; then
  msg "[!] This installer is made for Termux. 'pkg' command was not found."
  exit 1
fi

[ -f "$LAUNCHER_SRC" ] || { msg "[!] Missing scripts/launcher.sh"; exit 1; }
[ -f "$AVID_SRC" ] || { msg "[!] Missing scripts/avid.sh"; exit 1; }

msg "[+] Creating app directory: $APP_DIR"
mkdir -p "$APP_DIR/bin"

ask_update
msg "[i] This installer does NOT run pkg upgrade automatically anymore."
msg "[i] It installs only missing packages and keeps existing tools."

pkg_install_missing termux-api python git ruby curl fish figlet screenfetch nano wget ncurses-utils proot-distro nodejs openssh tmux jq ripgrep fd bat eza htop tree unzip zip

if [ ! -d "$HOME/storage" ]; then
  msg "[+] Requesting storage permission with termux-setup-storage..."
  termux-setup-storage || true
else
  msg "[✓] ~/storage already exists. Skipping termux-setup-storage."
fi

if ! has lolcat; then
  msg "[+] Installing lolcat via Ruby gem..."
  gem install lolcat --no-document || true
else
  msg "[✓] lolcat already installed."
fi

msg "[+] Checking Oh My Fish and batman theme..."
if has fish; then
  if fish -lc 'type -q omf' >/dev/null 2>&1; then
    msg "[✓] Oh My Fish already installed."
  else
    fish -lc 'curl -L https://github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish' || true
  fi
  if fish -lc 'omf theme 2>/dev/null | grep -qi batman' >/dev/null 2>&1; then
    msg "[✓] batman theme already active."
  else
    fish -lc 'omf install batman; or true' || true
    fish -lc 'omf theme batman; or omf batman; or true' || true
  fi
fi

msg "[+] Installing launcher, DevHub command and web panel files..."
cp "$LAUNCHER_SRC" "$LAUNCHER_DST"
chmod +x "$LAUNCHER_DST"
cp "$AVID_SRC" "$AVID_DST"
chmod +x "$AVID_DST"
rm -rf "$WEB_DST"
cp -R "$WEB_SRC" "$WEB_DST"
rm -rf "$AGENT_DST"
cp -R "$AGENT_SRC" "$AGENT_DST"
[ -n "${PREFIX:-}" ] && [ -d "$PREFIX/bin" ] && ln -sf "$AVID_DST" "$PREFIX/bin/avid" || true

if [ ! -f "$CONFIG_DST" ]; then
  cp "$CONFIG_SRC" "$CONFIG_DST"
  msg "[+] Created config: $CONFIG_DST"
else
  msg "[✓] Existing config kept: $CONFIG_DST"
  msg "[i] New defaults are available in: $CONFIG_SRC"
fi

msg "[+] Backing up and rewriting ~/.bashrc startup block..."
touch "$BASHRC"
cp "$BASHRC" "$BASHRC.avid-backup.$(date +%Y%m%d-%H%M%S)"
# User wants launcher to own startup. Keep clean but do not delete backups.
cat > "$BASHRC" <<EOF2
# ~/.bashrc generated by Avid Kiya Termux Ubuntu Launcher
# Old file was backed up as ~/.bashrc.avid-backup.DATE-TIME

export PATH="$APP_DIR/bin:\$PATH"

$MARK_BEGIN
if [ -f "$LAUNCHER_DST" ]; then
  . "$LAUNCHER_DST"
fi
$MARK_END
EOF2

msg "[+] Installing fish compatibility hook..."
mkdir -p "$FISH_CONF_DIR"
cat > "$FISH_CONF" <<EOF2
# Avid Kiya Launcher fish compatibility hook
set -gx PATH "$APP_DIR/bin" \$PATH
if status is-interactive
    if test -z "\$AK_LAUNCHER_SHOWN"; and test -f "$LAUNCHER_DST"
        set -gx AK_STARTED_FROM_FISH 1
        exec bash -i
    end
end
EOF2

msg ""
msg "[✓] Installed/updated successfully without reinstalling existing packages."
msg "[i] Startup menu restored: Termux / Ubuntu / Installer / Normal / DevHub"
msg "[i] Run full professional hub manually with: avid"
msg "[i] Run web panel with: avid web"
msg ""
msg "Restart Termux or run: exec bash -i"
