#!/usr/bin/env bash
set -euo pipefail

APP_DIR="$HOME/.termux-avid-kiya"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAUNCHER_SRC="$PROJECT_DIR/scripts/launcher.sh"
CONFIG_SRC="$PROJECT_DIR/config.example"
LAUNCHER_DST="$APP_DIR/launcher.sh"
CONFIG_DST="$APP_DIR/config"
BASHRC="$HOME/.bashrc"
FISH_CONF_DIR="$HOME/.config/fish/conf.d"
FISH_CONF="$FISH_CONF_DIR/avid-kiya-launcher.fish"
MARK_BEGIN="# >>> AVID_KIYA_TERMUX_UBUNTU_LAUNCHER >>>"
MARK_END="# <<< AVID_KIYA_TERMUX_UBUNTU_LAUNCHER <<<"

msg() { printf '%s\n' "$*"; }

if ! command -v pkg >/dev/null 2>&1; then
  msg "[!] This installer is made for Termux. 'pkg' command was not found."
  exit 1
fi

if [ ! -f "$LAUNCHER_SRC" ]; then
  msg "[!] Cannot find scripts/launcher.sh. Run install.sh from the project folder."
  exit 1
fi

msg "[+] Creating app directory: $APP_DIR"
mkdir -p "$APP_DIR"

msg "[+] Updating and upgrading Termux packages..."
pkg update -y || true
pkg upgrade -y || true

msg "[+] Installing classic Avid Kiya Termux dependencies..."
pkg install -y termux-api python git ruby curl fish figlet screenfetch nano wget ncurses-utils || true

msg "[+] Installing Ubuntu/proot dependencies..."
pkg install -y proot-distro || true

msg "[+] Requesting storage permission with termux-setup-storage..."
if command -v termux-setup-storage >/dev/null 2>&1; then
  termux-setup-storage || true
else
  msg "[i] termux-setup-storage not found. Skipping."
fi

if ! command -v lolcat >/dev/null 2>&1; then
  msg "[+] Installing lolcat via Ruby gem..."
  gem install lolcat --no-document || true
fi

msg "[+] Installing Oh My Fish and batman theme..."
if command -v fish >/dev/null 2>&1; then
  # Install Oh My Fish only if omf is not available.
  fish -lc 'type -q omf; or curl -L https://github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish' || true
  # Install and activate batman theme. Different OMF versions may use slightly different commands.
  fish -lc 'omf install batman; or true' || true
  fish -lc 'omf theme batman; or omf batman; or true' || true
else
  msg "[!] fish was not installed correctly. Skipping Oh My Fish."
fi

msg "[+] Installing launcher files..."
cp "$LAUNCHER_SRC" "$LAUNCHER_DST"
chmod +x "$LAUNCHER_DST"

if [ -f "$CONFIG_DST" ]; then
  cp "$CONFIG_DST" "$CONFIG_DST.avid-backup.$(date +%Y%m%d-%H%M%S)"
fi
# Final installer intentionally rewrites config so old settings do not break the final theme.
cp "$CONFIG_SRC" "$CONFIG_DST"

msg "[+] Backing up and rewriting ~/.bashrc from zero..."
touch "$BASHRC"
cp "$BASHRC" "$BASHRC.avid-backup.$(date +%Y%m%d-%H%M%S)"

# The user requested a clean ~/.bashrc. We intentionally overwrite it.
cat > "$BASHRC" <<EOF2
# ~/.bashrc generated by Avid Kiya Termux Ubuntu Launcher
# This is an upgraded version of the classic Avid Kiya Termux fish theme.
# Old file was backed up as ~/.bashrc.avid-backup.DATE-TIME

$MARK_BEGIN
if [ -f "$LAUNCHER_DST" ]; then
  . "$LAUNCHER_DST"
fi
$MARK_END
EOF2

msg "[+] Installing fish compatibility hook..."
mkdir -p "$FISH_CONF_DIR"
cat > "$FISH_CONF" <<EOF2
# Avid Kiya Launcher fish compatibility hook
# If Termux starts fish directly, jump to bash so ~/.bashrc can show the menu.
if status is-interactive
    if test -z "\$AK_LAUNCHER_SHOWN"; and test -f "$LAUNCHER_DST"
        set -gx AK_STARTED_FROM_FISH 1
        exec bash -i
    end
end
EOF2

msg ""
msg "[✓] Installed successfully."
msg "[i] Launcher:  $LAUNCHER_DST"
msg "[i] Config:    $CONFIG_DST"
msg "[i] Bashrc:    $BASHRC"
msg "[i] Fish hook: $FISH_CONF"
msg ""
msg "IMPORTANT: If you are currently inside fish, do NOT run: source ~/.bashrc"
msg "Instead restart Termux, or run: exec bash -i"
msg ""
msg "Menu option 1 = final Avid Kiya Termux banner + fish/batman"
msg "Menu option 3 = install/patch Ubuntu, then option 2 runs Ubuntu"
