#!/usr/bin/env bash
set -euo pipefail

APP_DIR="$HOME/.termux-avid-kiya"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAUNCHER_SRC="$PROJECT_DIR/scripts/launcher.sh"
CONFIG_SRC="$PROJECT_DIR/config.example"
LAUNCHER_DST="$APP_DIR/launcher.sh"
CONFIG_DST="$APP_DIR/config"
BASHRC="$HOME/.bashrc"
FISH_CONF_DIR="$HOME/.config/fish/conf.d"
FISH_CONF="$FISH_CONF_DIR/avid-kiya-launcher.fish"
MARK_BEGIN="# >>> AVID_KIYA_TERMUX_UBUNTU_LAUNCHER >>>"
MARK_END="# <<< AVID_KIYA_TERMUX_UBUNTU_LAUNCHER <<<"

msg() { printf '%s\n' "$*"; }

if ! command -v pkg >/dev/null 2>&1; then
  msg "[!] This installer is made for Termux. 'pkg' command was not found."
  exit 1
fi

if [ ! -f "$LAUNCHER_SRC" ]; then
  msg "[!] Cannot find scripts/launcher.sh. Run install.sh from the project folder."
  exit 1
fi

msg "[+] Creating app directory: $APP_DIR"
mkdir -p "$APP_DIR"

msg "[+] Updating Termux packages..."
pkg update -y || true

msg "[+] Installing required Termux packages..."
pkg install -y curl figlet ruby fish proot-distro ncurses-utils git wget nano || true

# screenfetch might not exist in every Termux repo. Try but do not fail.
pkg install -y screenfetch || true

if ! command -v lolcat >/dev/null 2>&1; then
  msg "[+] Installing lolcat via Ruby gem..."
  gem install lolcat --no-document || true
fi

msg "[+] Installing launcher files..."
cp "$LAUNCHER_SRC" "$LAUNCHER_DST"
chmod +x "$LAUNCHER_DST"

if [ ! -f "$CONFIG_DST" ]; then
  cp "$CONFIG_SRC" "$CONFIG_DST"
else
  msg "[i] Existing config kept: $CONFIG_DST"
fi

msg "[+] Backing up and rewriting ~/.bashrc from zero..."
touch "$BASHRC"
cp "$BASHRC" "$BASHRC.avid-backup.$(date +%Y%m%d-%H%M%S)"

# The user requested a clean ~/.bashrc. We intentionally overwrite it.
cat > "$BASHRC" <<EOF2
# ~/.bashrc generated by Avid Kiya Termux Ubuntu Launcher
# Old file was backed up as ~/.bashrc.avid-backup.DATE-TIME

$MARK_BEGIN
if [ -f "$LAUNCHER_DST" ]; then
  . "$LAUNCHER_DST"
fi
$MARK_END
EOF2

msg "[+] Installing fish compatibility hook..."
mkdir -p "$FISH_CONF_DIR"
cat > "$FISH_CONF" <<EOF2
# Avid Kiya Launcher fish compatibility hook
# If Termux starts fish directly, jump to bash so ~/.bashrc can show the menu.
if status is-interactive
    if test -z "\$AK_LAUNCHER_SHOWN"; and test -f "$LAUNCHER_DST"
        set -gx AK_STARTED_FROM_FISH 1
        exec bash -i
    end
end
EOF2

msg ""
msg "[✓] Installed successfully."
msg "[i] Launcher: $LAUNCHER_DST"
msg "[i] Config:   $CONFIG_DST"
msg "[i] Bashrc:   $BASHRC"
msg "[i] Fish hook: $FISH_CONF"
msg ""
msg "IMPORTANT: If you are currently inside fish, do NOT run: source ~/.bashrc"
msg "Instead restart Termux, or run: exec bash -i"
msg ""
msg "Use menu option 3 to install/patch Ubuntu, then option 2 to run it."
